package test;

import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

import bean.Ticket;
import bean.TicketVendingMachine;

public class TestMethodInjection {

	public static void main(String[] args) {
		ApplicationContext context = new ClassPathXmlApplicationContext("spring.xml");
		TicketVendingMachine ticketVendingMachine = (TicketVendingMachine) context.getBean("ticketVendingMachine");
		Ticket ticket = ticketVendingMachine.generateTicket();
		System.out.println("The ticket successfully generated by ticket vending machine = " + ticket);

	}

}
